<!DOCTYPE html>
<!-- saved from url=(0017)http://litten.me/ -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="dns-prefetch" href="/">
  <title>Handsome的博客</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="一个帅字贯穿一生">
<meta property="og:type" content="website">
<meta property="og:title" content="Handsome的博客">
<meta property="og:url" content="/index.html">
<meta property="og:site_name" content="Handsome的博客">
<meta property="og:description" content="一个帅字贯穿一生">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Handsome的博客">
<meta name="twitter:description" content="一个帅字贯穿一生">

<!--    <link rel="alternative" href="http://litten.me/atom.xml" title="Handsome的博客" type="application/atom+xml">-->


    <link rel="icon" href="/resources/exos/favicon.ico">

  <link rel="stylesheet" type="text/css" href="/resources/exos/main.2d9be4.css">
  <style type="text/css">
    #container.show {
      background: linear-gradient(200deg,#a0cfe4,#e8c37e);
    }
  </style>



<script src="/resources/exos/hm.js"></script>


<!--<link rel="stylesheet" href="/resources/editor/examples/css/style.css">-->
        <link rel="stylesheet" href="/resources/editor/css/editormd.css">
        <link type="text/css" rel="stylesheet" href="/resources/editor/lib/codemirror/codemirror.min.css">
        <link type="text/css" rel="stylesheet" href="/resources/editor/lib/codemirror/addon/dialog/dialog.css">
        <link type="text/css" rel="stylesheet" href="/resources/editor/lib/codemirror/addon/search/matchesonscrollbar.css">

        <script src="/resources/editor/examples/js/jquery.min.js"></script>
        <script id="-lib-marked-min" type="text/javascript" src="/resources/editor/lib/marked.min.js"></script>
        <script id="-lib-prettify-min" type="text/javascript" src="/resources/editor/lib/prettify.min.js"></script>
        <script type="text/javascript" src="/resources/editor/lib/raphael.min.js"></script>
        <script type="text/javascript" src="/resources/editor/lib/underscore.min.js"></script>
        <script type="text/javascript" src="/resources/editor/lib/sequence-diagram.min.js"></script>
        <script src="/resources/editor/lib/flowchart.min.js"></script>
        <script src="/resources/editor/lib/jquery.flowchart.min.js"></script>

        <script id="-lib-codemirror-codemirror-min" type="text/javascript" src="/resources/editor/lib/codemirror/codemirror.min.js"></script>
        <script id="-lib-codemirror-modes-min" type="text/javascript" src="/resources/editor/lib/codemirror/modes.min.js"></script>
        <script id="-lib-codemirror-addons-min" type="text/javascript" src="/resources/editor/lib/codemirror/addons.min.js"></script>


        <script src="/resources/editor/editormd.min.js"></script>

</head>

<body>
  <div id="container" q-class="show:isCtnShow"  class="">
    <canvas id="anm-canvas" class="anm-canvas" ></canvas>
    <div class="left-col" q-class="show:isShow">

<div class="overlay" style="background: #4d4d4d"></div>
<div class="intrude-less">
	<header id="header" class="inner">
		<a href="/" class="profilepic">
			<img src="/resources/exos/1231.png" class="js-avatar">
		</a>
		<hgroup>
		  <h1 class="header-author"><a href="/">Handsome</a></h1>
		</hgroup>

		<p class="header-subtitle">爱多甜蜜，充满香气</p>


		<nav class="header-menu">
			<ul>

				<li><a href="/">主页</a></li>

				<li><a href="/">相册</a></li>

			</ul>
		</nav>
		<nav class="header-smart-menu">


    			<a q-on="click: openSlider(e, 'innerArchive')" href="javascript:void(0)">所有文章</a>





    			<a q-on="click: openSlider(e, 'aboutme')" href="javascript:$('about_me').show();">关于我</a>


		</nav>
		<nav class="header-nav">
			<div class="social">

					<a class="github" target="_blank" href="https://github.com/yetHandsome/blog/" title="github"><i class="icon-github"></i></a>

					<a class="weibo" target="_blank" href="javascript:arert('忘记密码了！')" title="weibo"><i class="icon-weibo"></i></a>

					<a class="rss" target="_blank" href="/" title="rss"><i class="icon-rss"></i></a>

			</div>
		</nav>
	</header>
</div>

    </div>
    <div class="mid-col hide" q-class="show:isShow,hide:isShow|isFalse">

<nav id="mobile-nav">
  	<div class="overlay js-overlay" style="background: #4d4d4d"></div>
	<div class="btnctn js-mobile-btnctn">
  		<div class="slider-trigger list" q-on="click: openSlider(e)"><i class="icon icon-sort"></i></div>
	</div>
	<div class="intrude-less">
		<header id="header" class="inner">
			<div class="profilepic">
				<img src="/resources/exos/1231.png" class="js-avatar">
			</div>
			<hgroup>
			  <h1 class="header-author js-header-author">Handsome</h1>
			</hgroup>

			<p class="header-subtitle"><i class="icon icon-quo-left"></i>爱多美丽，充满香气<i class="icon icon-quo-right"></i></p>

			<nav class="header-nav">
				<div class="social">

						<a class="github" target="_blank" href="https://github.com/yetHandsome/blog/" title="github"><i class="icon-github"></i></a>

						<a class="weibo" target="_blank" href="/" title="weibo"><i class="icon-weibo"></i></a>

						<a class="rss" target="_blank" href="/" title="rss"><i class="icon-rss"></i></a>

				</div>
			</nav>

			<nav class="header-menu js-header-menu">
				<ul style="width: 50%">


					<li style="width: 50%"><a href="/">主页</a></li>

					<li style="width: 50%"><a href="/">相册</a></li>

				</ul>
			</nav>
		</header>
	</div>
	<div class="mobile-mask" style="display: none;" q-show="isShow"></div>
</nav>

      <div id="wrapper" class="body-wrap">
        <div class="menu-l">
          <div class="canvas-wrap">
            <canvas data-colors="#eaeaea" data-sectionheight="100" data-contentid="js-content" id="myCanvas1" class="anm-canvas"></canvas>
          </div>
          <div id="js-content" class="content-ll">

  <?php foreach($res2 as $k=>$v){ ?>
    <article id="post-diary-2017-1222-1229" class="article article-type-post  article-index" itemscope="" itemprop="blogPost">
  <div class="article-inner">

      <header class="article-header">


    <h1 itemprop="name">
      <a class="article-title" href="/?id=<?php echo $v['id']; ?>"><?php echo $v['title']; ?></a>
    </h1>



        <a href="/?id=<?php echo $v['id']; ?>" class="archive-article-date">
  	<time datetime="2017-12-29T02:36:00.000Z" itemprop="datePublished"><i class="icon-calendar icon"></i><?php echo $v['insert_time']; ?></time>
</a>

      </header>

    <div class="article-entry" itemprop="articleBody" style="text-align:left;">
        <div id='test-editormd<?php echo $v['id']; ?>'>
        <textarea style="display:none;"  class="editormd-markdown-textarea" placeholder="Enjoy Markdown! coding now..." name="markdown_doc">
<?php echo $v['markdown_doc_sort']; ?>
</textarea>
            </div>

        <?php if($is_doc == 0) { ?>
        <a class="article-more-a"  href="/?id=<?php echo $v['id']; ?>">more &gt;&gt;</a>
        <?php } ?>
    </div>









    <div class="article-info article-info-index">


	<div class="article-tag tagcloud">
		<i class="icon-price-tags icon"></i>
		<ul class="article-tag-list">

        		<li class="article-tag-list-item">
                            <?php  foreach($v['article_class2'] as $k2=>$v2){ ?>
                            <style>
                                 .tagcloud a.mycolor<?php echo $v['id']; ?>:before {
                                       border-right-color: <?php echo $v2['color']; ?>;
                                   }
                             </style>
                             <a href="javascript:void(0)" class="js-tag article-tag-list-link color3 mycolor<?php echo $v2['id']; ?>" style="background:<?php echo $v2['color']; ?>" ><?php echo $v2['name']; ?></a>
                            <?php } ?>


        		</li>

		</ul>
	</div>



      <?php if($is_doc == 0) { ?>
        <p class="article-more-link">
          <a class="article-more-a" href="/?id=<?php echo $v['id']; ?>">展开全文 &gt;&gt;</a>
        </p>
      <?php }else{ ?>
        <div class="share-btn share-icons tooltip-left">
  <div class="tooltip tooltip-east">
    <span class="tooltip-item">
      <a href="javascript:;" class="share-sns share-outer">
        <i class="icon icon-share"></i>
      </a>
    </span>
    <span class="tooltip-content">
      <div class="share-wrap">
        <div class="share-icons">
          <a class="weibo share-sns" href="javascript:;" data-type="weibo">
            <i class="icon icon-weibo"></i>
          </a>
          <a class="weixin share-sns wxFab" href="javascript:;" data-type="weixin">
            <i class="icon icon-weixin"></i>
          </a>
          <a class="qq share-sns" href="javascript:;" data-type="qq">
            <i class="icon icon-qq"></i>
          </a>
          <a class="douban share-sns" href="javascript:;" data-type="douban">
            <i class="icon icon-douban"></i>
          </a>
          <a class="qzone share-sns" href="javascript:;" data-type="qzone">
            <i class="icon icon-qzone"></i>
          </a>
          <a class="facebook share-sns" href="javascript:;" data-type="facebook">
            <i class="icon icon-facebook"></i>
          </a>
          <a class="twitter share-sns" href="javascript:;" data-type="twitter">
            <i class="icon icon-twitter"></i>
          </a>
          <a class="google share-sns" href="javascript:;" data-type="google">
            <i class="icon icon-google"></i>
          </a>
        </div>
      </div>
    </span>
  </div>
</div>

        <script src="/resources/exos/jquery.qrcode.js"></script>
  <script src="/resources/exos/utf.js"></script>
  <!--<script src="/resources/exos/qrcode.js"></script>-->

      <div class="page-modal wx-share js-wx-box">
          <a class="close js-modal-close" href="javascript:;"><i class="icon icon-close"></i></a>
          <p>扫一扫，分享到微信</p>
          <div class="wx-qrcode">
            <div id="url-code"></div>
            <!-- <img src=""> -->
          </div>
      </div>
      <div class="mask js-mask"></div>
      <script>
      $("#url-code").qrcode({
            render: "canvas",    //设置渲染方式，有table和canvas，使用canvas方式渲染性能相对来说比较好
            text: '<?php echo $codeSrc ?>',  //扫描二维码后显示的内容,可以直接填一个网址，扫描二维码后自动跳向该链接
            width: "152",               //二维码的宽度
            height: "152",              //二维码的高度
            typeNumber: -1,//计算模式
            correctLevel: 2,//二维码纠错级别
            background: "#ffffff",       //二维码的后景色
            foreground: "#000000",        //二维码的前景色
            src: '/resources/exos/litten4.png'             //二维码中间的图片
          });
      </script>
      <?php } ?>


      <div class="clearfix"></div>
    </div>
  </div>
</article>

<aside class="wrap-side-operation">
    <div class="mod-side-operation">

        <div class="jump-container" id="js-jump-container" style="display:none;">
            <a href="javascript:void(0)" class="mod-side-operation__jump-to-top">
                <i class="icon-font icon-back"></i>
            </a>
            <div id="js-jump-plan-container" class="jump-plan-container" style="top: -11px;">
                <i class="icon-font icon-plane jump-plane"></i>
            </div>
        </div>


    </div>
</aside>


              <script type="text/javascript">
            var testEditor<?php echo $v['id']; ?>;
            $(function () {
                testEditor<?php echo $v['id']; ?> = editormd.markdownToHTML("test-editormd<?php echo $v['id']; ?>", {
                    path : '/resources/editor/lib/',
                    htmlDecode      : "style,script,iframe",  // you can filter tags decode
                    emoji           : true,
                    taskList        : true,
                    tex             : true,  // 默认不解析
                    flowChart       : true,  // 默认不解析
                    sequenceDiagram : true,  // 默认不解析
                });
            });
        </script>
        <?php if($is_doc && $gitment) { ?>
        <div id="gitment_container" style="margin: 30px;position: relative;"></div>
        <!-- <link rel="stylesheet" href="https://imsun.github.io/gitment/style/default.css">
        <script src="https://imsun.github.io/gitment/dist/gitment.browser.js"></script> -->
        <link rel="stylesheet" href="/resources/gitment/default.css">
        <script src="/resources/gitment/gitment.browser.js"></script>
        <script>
        var gitment = new Gitment({
          id: '<?php echo $v['id']; ?>', // 可选。默认为 location.href
          owner: '<?php echo $owner; ?>',
          repo: '<?php echo $repo; ?>',
          oauth: {
            client_id: '<?php echo $client_id; ?>',
            client_secret: '<?php echo $client_secret; ?>',
          },
        })
        gitment.render('gitment_container')
        </script>
        <?php }?>

  <?php } ?>

        <style>
            .editormd{
                border: 0px;
            }
            a.editormd-preview-close-btn{
                display: none;
            }
    </style>





  <?php if(1 == 0 && $is_doc == 0) { ?>
    <nav id="page-nav"><a class="extend prev disabled" rel="prev">« Prev</a>
      <span class="page-number current">1</span><a class="page-number" href="http://litten.me/page/2/">2</a><a class="page-number" href="http://litten.me/page/3/">3</a><span class="space">…</span><a class="page-number" href="http://litten.me/page/10/">10</a><a class="extend next" rel="next" href="http://litten.me/page/2/">Next »</a>
    </nav>
  <?php } ?>

    <nav id="article-nav">
        <?php if(isset($prve_doc) && $prve_doc) { ?>
    <a href="/?id=<?php echo $prve_doc['id']; ?>" id="article-nav-newer" class="article-nav-link-wrap">
      <i class="icon-circle-left"></i>
      <div class="article-nav-title"><?php echo $prve_doc['title']; ?></div>
    </a>
   <?php } ?>

   <?php if(isset($next_doc) && $next_doc) { ?>
    <a href="/?id=<?php echo $next_doc['id']; ?>" id="article-nav-older" class="article-nav-link-wrap">
      <div class="article-nav-title"><?php echo $next_doc['title']; ?></div>
      <i class="icon-circle-right"></i>
    </a>
   <?php } ?>
    </nav>





          </div>
        </div>
      </div>
      <footer id="footer">
  <div class="outer">
    <div id="footer-info">
    	<div class="footer-left">
    		© 2018 Handsome
    	</div>
      	<div class="footer-right">
      		<a href="http://hexo.io/" target="_blank">Hexo</a>  Theme <a href="https://github.com/litten/hexo-theme-yilia" target="_blank">Yilia</a> by Handsome
      	</div>
    </div>
  </div>
</footer>
    </div>

    <script>
	var yiliaConfig = {
		mathjax: false,
		isHome: true,
		isPost: false,
		isArchive: false,
		isTag: false,
		isCategory: false,
		open_in_new: true,
		toc_hide_index: true,
		root: "/resources/exos/",
		innerArchive: true,
		showTags: false
	}
</script>
<script src="/resources/exos/main.js"></script>
<script src="/resources/exos/main.2d9be4.js"></script>
<script>!function(){!function(e){var t=document.createElement("script");document.getElementsByTagName("body")[0].appendChild(t),t.setAttribute("src",e)}("/resources/exos/slider.e37972.js")}()</script>



<div class="tools-col hide" q-class="show:isShow,hide:isShow|isFalse" q-on="click:stop(e)">
  <div class="tools-nav header-menu">














    <ul style="width: 70%">



      <li style="width: 50%" q-on="click: openSlider(e, 'innerArchive')"><a href="javascript:void(0)" q-class="active:innerArchive">所有文章</a></li>





      <li style="width: 50%" q-on="click: openSlider(e, 'aboutme')"><a href="javascript:$('about_me').show();" q-class="active:aboutme">关于我</a></li>


    </ul>
  </div>
  <div class="tools-wrap">

    	<section class="tools-section tools-section-all" q-show="innerArchive" style="">
        <div class="search-wrap">


        <script>
            older_val = '';
           function showTage(a){
               if(older_val == a){
                   return false;
               }else{
                   var search_li = $('.search-li');
                   if(a.length == 0){
                       search_li.show();
                       return false;
                   }
                   search_li.hide();
                   search_span = search_li.find('span.justspan');
                   search_span.each(function(i){
                        var l   = a.length;
                        var w   = $(this).html();
                        var s_w = w.substr(0,l-1);
                        if('#'+s_w == a){
                            $(this).parents('li.search-li').show();
                        }
                      });
               }
               older_val = a;
           }
           setInterval(function(){
               var a = $('#search-ipt').val();
               showTage(a);
           },200)
        </script>
        <input class="search-ipt"  id='search-ipt' oninput="showTage(this.value)" q-model="search" type="text" placeholder="find something…">
          <i class="icon-search icon" q-show="search|isEmptyStr"></i>
          <i class="icon-close icon" q-show="search|isNotEmptyStr" q-on="click:clearChose(e)" style="display: none;"></i>
        </div>
        <div class="widget tagcloud search-tag">
          <p class="search-tag-wording">tag:</p>
          <label class="search-switch">
            <input type="checkbox" q-on="click:toggleTag(e)" q-attr="checked:showTags">
          </label>

        <ul class="article-tag-list" q-show="showTags" style="display: none;">
             <?php foreach($article_class as $k=>$v){ ?>
              <li class="article-tag-list-item">
                  <style>
                      .tagcloud a.mycolor<?php echo $v['id']; ?>:before {
                            border-right-color: <?php echo $v['color']; ?>;
                        }
                  </style>
                  <a   class="js-tag color3 mycolor<?php echo $v['id']; ?>" style="background:<?php echo $v['color']; ?>"><?php echo $v['name']; ?></a>
              </li>
             <?php } ?>
            <div class="clearfix"></div>
          </ul>
        </div>
        <ul class="search-ul">

          <p></p>

           <?php foreach($res as $k=>$v){ ?>
          <li  class="search-li" q-show="isShow">
            <a q-attr="href:path|urlformat" class="search-title" href="/?id=<?php echo $v['id']; ?>"><i class="icon-quo-left icon"></i><span q-text="title"><?php echo $v['title']; ?></span></a>
            <p class="search-time">
              <i class="icon-calendar icon"></i>
              <span q-text="date|dateformat"><?php echo $v['insert_time']; ?></span>
            </p>
            <p class="search-tag">
              <i class="icon-price-tags icon"></i>
               <?php  foreach($v['article_class2'] as $k2=>$v2){ ?>
               <span q-on="click:choseTag(e, name)"   q-text="name|tagformat" class="justspan" style="color:<?php echo $v2['color']; ?>"><?php echo $v2['name']; ?></span>
               <?php } ?>
              <!--q-repeat-->
            </p>
          </li>
          <?php } ?>


          <!--q-repeat-->
        </ul>

    	</section>





    	<section class="tools-section tools-section-me" id="about_me" q-show="aboutme" >

  	  		<div class="aboutme-wrap" id="js-aboutme-x">拿走爱<br/>世界将变成一座坟墓<br/><br>一帅<br/>热爱大海与沙滩<br>擅长PHP、会python，目前学go<br>技术只是我的业余爱好<br/>真实身份...</div>

    	</section>

  </div>

</div>
    <!-- Root element of PhotoSwipe. Must have class pswp. -->

  </div>
<!--    <script src="/resources/exos/slider.e37972.js"></script>-->

</body>
</html>
