<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Simpla Admin by yetshine.com</title>
<!--                       CSS                       -->
<!-- Reset Stylesheet -->
<link rel="stylesheet" href="/resources/css/reset.css" type="text/css" media="screen" />
<!-- Main Stylesheet -->
<link rel="stylesheet" href="/resources/css/style.css" type="text/css" media="screen" />
<!-- Invalid Stylesheet. This makes stuff look pretty. Remove it if you want the CSS completely valid -->
<link rel="stylesheet" href="/resources/css/invalid.css" type="text/css" media="screen" />
<!--                       Javascripts                       -->
<!-- jQuery -->
<script type="text/javascript" src="/resources/scripts/jquery-1.3.2.min.js"></script>
<!--<script type="text/javascript" src="/resources/scripts/jquery-1.7.1.min.js"></script>-->
<script type="text/javascript" src="/resources/js/jquery.qrcode.js"></script>
<script type="text/javascript" src="/resources/js/utf.js"></script>
<!-- jQuery Configuration -->
<script type="text/javascript" src="/resources/scripts/simpla.jquery.configuration.js"></script>
<!-- Facebox jQuery Plugin -->
<script type="text/javascript" src="/resources/scripts/facebox.js"></script>
<!-- jQuery WYSIWYG Plugin -->
<script type="text/javascript" src="/resources/scripts/jquery.wysiwyg.js"></script>
<!-- jQuery Datepicker Plugin -->
<!--<script type="text/javascript" src="/resources/scripts/jquery.datePicker.js"></script>
<script type="text/javascript" src="/resources/scripts/jquery.date.js"></script>-->
</head>
    <body style="background:none;">
<div id="body-wrapper" style="background:none;">
  
<div id="main-content" style="padding:0;margin:0;">
    <!-- Main Content Section with everything -->
    <noscript>
    <!-- Show a notification if the user has disabled javascript -->
    <div class="notification error png_bg">
      <div> Javascript is disabled or is not supported by your browser. Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.
        Download From <a href="http://www.exet.tk">exet.tk</a></div>
    </div>
    </noscript>
    <!-- Page Head -->
    <h2>Welcome yetshine.com</h2>
    <p id="page-intro">What would you like to do?</p>
    <ul class="shortcut-buttons-set">
      <li><a class="shortcut-button" href="#"><span> <img src="/resources/images/icons/pencil_48.png" alt="icon" /><br />
        Write an Article </span></a></li>
      <li><a class="shortcut-button" href="#"><span> <img src="/resources/images/icons/paper_content_pencil_48.png" alt="icon" /><br />
        Create a New Page </span></a></li>
      <li><a class="shortcut-button" href="#"><span> <img src="/resources/images/icons/image_add_48.png" alt="icon" /><br />
        Upload an Image </span></a></li>
      <li><a class="shortcut-button" href="#"><span> <img src="/resources/images/icons/clock_48.png" alt="icon" /><br />
        Add an Event </span></a></li>
      <li><a class="shortcut-button" href="#messages" rel="modal"><span> <img src="/resources/images/icons/comment_48.png" alt="icon" /><br />
        Open Modal </span></a></li>
    </ul>
    <!-- End .shortcut-buttons-set -->
    <div class="clear"></div>
    <!-- End .clear -->
    <?php if(isset($msg3)){?>
    <div class="notification success png_bg"> <a href="#" class="close"><img src="/resources/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
        <div> <?php echo $msg3; ?> </div>
    </div>
    <?php } ?>
    
    <?php if(isset($msg4)){?>
    <div class="notification error png_bg"> <a href="#" class="close"><img src="/resources/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
        <div> <?php echo $msg4; ?> </div>
    </div>
    <?php } ?>
      <div class="content-box column-left">
      <div class="content-box-header">
        <h3>Change your passwor</h3>
      </div>
      <!-- End .content-box-header -->
      <div class="content-box-content">
        <div class="tab-content default-tab">
            <form action="/index/index/changepasswd" method="post">
                <fieldset>
                    <p>
                    <label>old password:</label>
                    <input class="text-input medium-input datepicker" type="password" id="medium-input" name="oldpassword" />
                        <?php if(isset($msg)){?><span class="input-notification error png_bg"><?php echo $msg; ?></span> <?php } ?>
                    </p>

                    <p>
                    <label style="width: 120px">new password:</label>
                    <input class="text-input medium-input datepicker" type="password" id="medium-input" name="newpassword" />
                    </p>


                    <p>
                    <label >input new password again:</label>
                    <input  class="text-input medium-input datepicker" type="password" id="medium-input"  name="newpassword2" />
                    <?php if(isset($msg2)){?><span class="input-notification error png_bg"><?php echo $msg2; ?></span> <?php } ?>
                    </p>


                    <input class="button" type="submit" value="Change" />
                </fieldset>
            </form>
        </div>
        <!-- End #tab3 -->
      </div>
      <!-- End .content-box-content -->
    </div>
    <!-- End .content-box -->
    <div class="content-box column-right closed-box">
      <div class="content-box-header">
        <!-- Add the class "closed" to the Content box header to have it closed by default -->
        <h3>Change your verify code</h3>
      </div>
      <!-- End .content-box-header -->
      <div class="content-box-content">
        <div class="tab-content default-tab">
            <div class="content-box column-left" style="border:0px;width: 70%;">
        <form action="/index/index/changeverifycode" method="post">
        <fieldset>
        <p>
          <label>open verify</label>
          <input type="radio" name="open_verify" value="1" <?php if($open_verify){?>  checked="chencked" <?php } ?> />
          On
          <input type="radio" name="open_verify" value="0" <?php if(!$open_verify){?>checked="chencked" <?php } ?> />
          Off
        </p>
        <p>
        <p>
        <label>old verify code:</label>
        <input class="text-input medium-input datepicker" type="text" id="medium-input" value="<?php echo $verifyCode;?>" name="nothig" />
        </p>
            
        
        
        <p>
        <label>new verify code:</label>
        <input class="text-input medium-input datepicker" type="text" id="medium-input" name="newverifycode" />
        <?php if(isset($msg5)){?><span class="input-notification error png_bg"><?php echo $msg5; ?></span> <?php } ?>
        <?php if(isset($msg6)){?><span class="input-notification error png_bg"><?php echo $msg6; ?></span> <?php } ?>
        <br>
        <small>长度16位,只能包含如下字符串:A~Z和2~7</small>
        </p>
        <input class="button" type="submit" value="Change" />
        </fieldset>
        </form>
            </div>
            <div class="content-box column-right" style="border:0px;width: 30%;">
                <div id="code" style="margin-top: 35px"></div><br>
                <small>搜索Google authenticator,下载APP,APP扫码即可</small>
            </div>
        </div>
        <!-- End #tab3 -->
      </div>
      <!-- End .content-box-content -->
    </div>
    
    <!-- End .content-box -->

    <div class="clear"></div>

    <!-- End Notifications 
<div id="footer"> <small>
      <!-- Remove this notice or replace it with whatever you want -->
      &#169; Copyright 2010 Your Company | Powered by <a href="http://yetshine.com">admin templates</a> | <a href="#">Top</a> </small> </div>
    <!-- End #footer -->
  </div>
  <!-- End #main-content -->
</div>
</body>
    <script type="text/javascript">
    var qrcode_url = "<?php echo $qrcode_url; ?>";
    if (qrcode_url == null){

    }else{
        $("#code").qrcode({ 
            width: 120,
            height: 120,
            text: qrcode_url
        });
        $(function(){
            var type = "png";
            var oCanvas = document.getElementById("myCanvas");
            var imgData = oCanvas.toDataURL(type);
            var qrcode = document.getElementById("code");
            qrcode.src = imgData;
        });

    }
</script>
<!-- Download From www.exet.tk-->
</html>