<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Simpla Admin by yetshine.com</title>
        <!--                       CSS                       -->
        <!-- Reset Stylesheet -->
        <link rel="stylesheet" href="/resources/css/reset.css" type="text/css" media="screen" />
        <!-- Main Stylesheet -->
        <link rel="stylesheet" href="/resources/css/style.css" type="text/css" media="screen" />
        <!-- Invalid Stylesheet. This makes stuff look pretty. Remove it if you want the CSS completely valid -->
        <link rel="stylesheet" href="/resources/css/invalid.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/resources/css/colpick.css" type="text/css" media="screen" />
        <!--                       Javascripts                       -->
        <!-- jQuery -->
        <!--<script type="text/javascript" src="/resources/scripts/jquery-1.3.2.min.js"></script>-->
        <script type="text/javascript" src="/resources/js/jquery.min.js"></script>
        <script type="text/javascript" src="/resources/js/colpick.js"></script>
        <!-- jQuery Configuration -->
        <script type="text/javascript" src="/resources/scripts/simpla.jquery.configuration.js"></script>
        <!-- Facebox jQuery Plugin -->
        <script type="text/javascript" src="/resources/scripts/facebox.js"></script>
        <!-- jQuery WYSIWYG Plugin -->
        <script type="text/javascript" src="/resources/scripts/jquery.wysiwyg.js"></script>
        <!-- jQuery Datepicker Plugin -->
        <!--<script type="text/javascript" src="/resources/scripts/jquery.datePicker.js"></script>
        <script type="text/javascript" src="/resources/scripts/jquery.date.js"></script>-->
            <link rel="icon" href="/resources/exos/favicon.ico">
    </head>

    <body style="background:none;">
        <div id="body-wrapper" style="background:none;">

            <div id="main-content" style="padding:0;margin:0;">
                <!-- Main Content Section with everything -->
                <noscript>
                    <!-- Show a notification if the user has disabled javascript -->
                    <div class="notification error png_bg">
                        <div> Javascript is disabled or is not supported by your browser. Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.
                            Download From <a href="http://www.exet.tk">exet.tk</a></div>
                    </div>
                </noscript>
                <!-- Page Head -->
                <h2>Welcome yetshine.com</h2>
                <p id="page-intro">What would you like to do?</p>
                <ul class="shortcut-buttons-set">
                    <li><a class="shortcut-button" href="#"><span> <img src="/resources/images/icons/pencil_48.png" alt="icon" /><br />
                                Write an Article </span></a></li>
                    <li><a class="shortcut-button" href="#"><span> <img src="/resources/images/icons/paper_content_pencil_48.png" alt="icon" /><br />
                                Create a New Page </span></a></li>
                    <li><a class="shortcut-button" href="#"><span> <img src="/resources/images/icons/image_add_48.png" alt="icon" /><br />
                                Upload an Image </span></a></li>
                    <li><a class="shortcut-button" href="#"><span> <img src="/resources/images/icons/clock_48.png" alt="icon" /><br />
                                Add an Event </span></a></li>
                    <li><a class="shortcut-button" href="#tab2" rel="modal"><span> <img src="/resources/images/icons/comment_48.png" alt="icon" /><br />
                                Open Modal </span></a></li>
                </ul>
                <!-- End .shortcut-buttons-set -->
                <div class="clear"></div>
                <!-- End .clear -->


                <div class="content-box">
                    <!-- Start Content Box -->
                    <div class="content-box-header">
                        <h3>Content box</h3>
                        <ul class="content-box-tabs">
                            <li><a href="#tab1" class="default-tab">Table</a></li>
                            <!-- href must be unique and match the id of target div -->
                            <li><a href="#tab2">Forms</a></li>
                        </ul>
                        <div class="clear"></div>
                    </div>
                    <!-- End .content-box-header -->
                    <div class="content-box-content">
                        <div class="tab-content default-tab" id="tab1">
                            <!-- This is the target div. id must match the href of this div's tab -->
                            <?php if (isset($msg)) { ?>
                                <div class="notification success png_bg"> <a href="#" class="close"><img src="/resources/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
                                    <div> <?php echo $msg; ?> </div>
                                </div>
                            <?php } ?>

                            <?php if (isset($msg2)) { ?>
                                <div class="notification error png_bg"> <a href="#" class="close"><img src="/resources/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
                                    <div> <?php echo $msg2; ?> </div>
                                </div>
                            <?php } ?>
                            <?php if (count($res) == 0) { ?>
                                <div class="notification attention png_bg"> <a href="#" class="close"><img src="/resources/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
                                    <div>  主人太懒还没有发表任何文章</div>
                                </div>
                            <?php } else { ?>
                                <table>
                                    <thead>
                                        <tr>
                          <!--                <th>
                                            <input class="check-all" type="checkbox" />
                                          </th>-->
                                            <th>ID</th>
                                            <th>标题</th>
                                            <th>作者</th>
                                            <th>添加时间</th>
                                            <th>最后修改时间</th>
                                            <th>所属分类</th>
                                            <th>是否可见</th>
                                            <!--<th>最开始可见时间</th>-->
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <td colspan="8">

                                            </td>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        <?php foreach ($res as $k => $v) { ?>


                                            <tr>

                                                <td><?php echo $v['id']; ?></td>
                                                <td><?php echo $v['title']; ?></td>
                                                <td><?php echo $v['username']; ?></td>
                                                <td><?php echo $v['insert_time']; ?></td>
                                                <td><?php echo $v['update_time']; ?></td>
                                                <td><?php echo $v['article_class2']; ?></td>
                                                <td><?php echo $v['is_show2']; ?></td>
                                                <!--<td><?php echo $v['show_time2']; ?></td>-->
                                                <td>
                                                    <!-- Icons -->
                                                    <!--<a href="#" title="Edit"><img src="/resources/images/icons/pencil.png" alt="Edit" /></a>--> 
                                                    <a href="#tab3"  title="Delete" class="giveMeAlert" onclick="delArtile('<?php echo $v['id']; ?>', '<?php echo $v['title']; ?>')" ><img src="/resources/images/icons/cross.png" alt="Delete" /></a> 
                                                    <a href="/index/article/getarticle?id=<?php echo $v['id']; ?>"  title="Edit Meta" ><img src="/resources/images/icons/hammer_screwdriver.png" alt="Edit Meta" /></a> 
                                                </td>
                                            </tr>
                                        <?php } ?>		  
                                    </tbody>
                                </table>
                            <?php } ?>
                        </div>
                        <!-- End #tab1 -->
                        <div class="tab-content" id="tab2">
                            <form action="/index/article/AddArticleClass" method="post">
                                <fieldset>
                                    <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
                                    <p>
                                        <label>标题</label>
                                        <input class="text-input small-input" type="text" id="medium-input" name="title" />

                                        <br />
                                        <small></small> 
                                    </p>

                                    <p>
                                        <label>首次可见时间</label>
                                        <input type="text" name="show_time" />
                                    </p>

                                    <p>
                                        <label>是否可见</label>
                                        <input type="radio" name="is_show" value="1" checked='checked' /> 可见
                                        <input type="radio" name="is_show" value="0" /> 隐藏
                                    </p>

                                    <p>
                                        <label>所属分类</label>
                                        <?php foreach ($article_class as $k => $v) { ?>
                                            <input type="checkbox" name="show_time" value="<?php echo $v['id']; ?>"  /> <span style="color:<?php echo $v['color']; ?> "> <?php echo $v['name']; ?> </span>
                                        <?php } ?>

                                    </p>
                                    <p>
                                        <label>Textarea with WYSIWYG</label>
                                        <textarea class="text-input textarea wysiwyg" id="textarea" name="textfield" cols="79" rows="15"></textarea>
                                    </p>

                                    <p>
                                        <input class="button" type="submit" value="Submit" />
                                    </p>
                                </fieldset>
                                <div class="clear"></div>
                                <!-- End .clear -->
                            </form>
                        </div>
                        <!-- End #tab2 -->
                        <div class="tab-content" id="tab3" style="display: none">
                            <h2 style="margin-left:130px">删除</h2>
                            <form action="/index/article/DelArticle" method="post">
                                <fieldset>
                                    <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
                                    <p>
                                        <label>确定是否要删除id:<span id="id"></span>,《<span id="title"></span>》，删除将不可找回，建议为隐藏</label>
                                        <input class="text-input small-input" type="hidden" id="delid" name="id" />
                                    </p>

                                    <p>
                                        <input class="button" type="submit" name='submit' value="删除" />
                                        <input class="button" type="submit" name='submit' value="隐藏" />
                                    </p>
                                </fieldset>
                                <div class="clear"></div>
                                <!-- End .clear -->
                            </form>
                        </div>
                    </div>
                    <!-- End .content-box-content -->
                </div>


                <div class="clear"></div>

                <!-- End Notifications 
            <div id="footer"> <small>
                <!-- Remove this notice or replace it with whatever you want -->
                &#169; Copyright 2010 Your Company | Powered by <a href="http://yetshine.com">admin templates</a> | <a href="#">Top</a> </small> </div>
            <!-- End #footer -->

            <!-- End #main-content -->
        </div>
    </body>
    <script>
        function delArtile(id, title) {
            $('#delid').val(id);
            $('#id').html(id);
            $('#title').html(title);
        }
        $(document).ready(function () {
            $('.giveMeAlert').facebox();
        });
    </script>
    <!-- Download From www.exet.tk-->
</html>